[package]
name = "rdm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
byteorder = "1.4.3"
ux = "0.1.5"
yansi = "0.5.1"
thiserror = "1.0.37"